# Generated by Django 4.2.5 on 2023-12-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_useraccount_kycstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="pancard_no",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="PanCard Number"
            ),
        ),
    ]
