# Generated by Django 4.2.5 on 2023-12-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_useraccount_fullname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="platform_id",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                unique=True,
                verbose_name="Platform id",
            ),
        ),
    ]
