# Generated by Django 4.2.5 on 2023-12-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_useraccount_platform_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="unique_sequence",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Unique sequence"
            ),
        ),
    ]
