# Generated by Django 4.2.5 on 2023-12-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_useraccount_unique_sequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="unique_sequence",
            field=models.IntegerField(
                blank=True, default=1, null=True, verbose_name="Unique sequence"
            ),
        ),
    ]
