# Generated by Django 4.2.3 on 2023-12-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_useraccount_unique_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='userWallet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='User Wallet'),
        ),
    ]
