# Generated by Django 4.2.3 on 2023-12-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_useraccount_userwallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='userWallet',
        ),
    ]
