# Generated by Django 4.2.5 on 2024-01-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_remove_useraccount_userwallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="acc_name",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Account Name"
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="acc_no",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Account Number"
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="acc_type",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Account Type"
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="ifsc",
            field=models.CharField(blank=True, max_length=500, verbose_name="IFSC"),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="payment_mode",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Payment Mode"
            ),
        ),
    ]
