# Generated by Django 4.2.5 on 2024-05-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_useraccount_acc_name_useraccount_acc_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="profile_img",
            field=models.ImageField(
                blank=True, upload_to="ProfileImg/", verbose_name="Profile Photo"
            ),
        ),
    ]
