# Generated by Django 4.2.5 on 2024-05-05 10:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_useraccount_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="profile_img",
            field=models.ImageField(
                blank=True,
                upload_to=core.models.document_file_path,
                verbose_name="Profile Photo",
            ),
        ),
    ]
