# Generated by Django 4.2.10 on 2024-08-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_useraccount_pay_sprint_ref_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='pay_sprint_ref_no',
        ),
    ]
