# Generated by Django 4.2.10 on 2024-08-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_useraccount_pay_sprint_ref_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='pay_sprint_ref_no',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='PaySprint Ref Number'),
        ),
    ]
