# Generated by Django 4.2.5 on 2023-11-22 17:42

import backend.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequiredDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Document Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KycInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "documentFile",
                    models.FileField(
                        upload_to=backend.models.document_file_path,
                        verbose_name="Document File",
                    ),
                ),
                (
                    "documentComment",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Document Comment",
                    ),
                ),
                (
                    "documentName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.requireddocument",
                        verbose_name="Document Name",
                    ),
                ),
                (
                    "userAccount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Linked User",
                    ),
                ),
            ],
            options={
                "unique_together": {("userAccount", "documentName")},
            },
        ),
    ]
