# Generated by Django 4.2.5 on 2023-11-26 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0002_remove_kycinformation_documentfile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serviceName",
                    models.CharField(max_length=150, verbose_name="Service Name"),
                ),
                (
                    "serviceDescription",
                    models.CharField(
                        max_length=150, verbose_name="Service Description"
                    ),
                ),
                (
                    "userAccount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Linked User",
                    ),
                ),
            ],
        ),
    ]
