# Generated by Django 4.2.5 on 2023-12-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_otherservices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycinformation",
            name="documentName",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Document Name"
            ),
        ),
        migrations.DeleteModel(
            name="RequiredDocument",
        ),
    ]
