# Generated by Django 4.2.3 on 2023-12-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_wallet_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='txtId',
            new_name='txnId',
        ),
    ]
