# Generated by Django 4.2.3 on 2023-12-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_txtid_transaction_txnid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='WalletTransaction',
        ),
    ]
