# Generated by Django 4.2.3 on 2023-12-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_transaction_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Transaction Type'),
        ),
    ]
