# Generated by Django 4.2.5 on 2023-12-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0009_wallettransaction_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="unique_sequence",
            field=models.IntegerField(
                blank=True, default=1, null=True, verbose_name="Unique sequence"
            ),
        ),
    ]
