# Generated by Django 4.2.3 on 2023-12-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_wallettransaction_unique_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRTxnCallbackByEko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_status', models.CharField(max_length=50, verbose_name='tx_status')),
                ('amount', models.CharField(max_length=50, verbose_name='amount')),
                ('tds', models.CharField(max_length=50, verbose_name='tds')),
                ('txstatus_desc', models.CharField(max_length=50, verbose_name='txstatus_desc')),
                ('fee', models.CharField(max_length=50, verbose_name='fee')),
                ('gst', models.CharField(max_length=50, verbose_name='gst')),
                ('tid', models.CharField(max_length=50, verbose_name='tid')),
                ('client_ref_id', models.CharField(max_length=50, verbose_name='client_ref_id')),
                ('old_tx_status', models.CharField(max_length=50, verbose_name='old_tx_status')),
                ('partners_commision', models.CharField(max_length=50, verbose_name='partners_commision')),
                ('service_code', models.CharField(max_length=50, verbose_name='service_code')),
                ('old_tx_status_desc', models.CharField(max_length=50, verbose_name='old_tx_status_desc')),
                ('bank_ref_num', models.CharField(max_length=50, verbose_name='bank_ref_num')),
                ('timestamp', models.CharField(max_length=50, verbose_name='timestamp')),
            ],
        ),
    ]
