# Generated by Django 4.2.5 on 2023-12-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0013_qrtxncallbackbyeko"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "QrPaymentService",
                    models.BooleanField(
                        default=False, verbose_name="QR Payment Status"
                    ),
                ),
                (
                    "AepsService",
                    models.BooleanField(default=False, verbose_name="AEPS Status"),
                ),
            ],
        ),
    ]
