# Generated by Django 4.2.5 on 2023-12-24 10:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0015_servicestatus_useraccount"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ServiceStatus",
            new_name="ServiceActivation",
        ),
    ]
