# Generated by Django 4.2.7 on 2023-12-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_aepstxncallbackbyeko'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aepstxncallbackbyeko',
            name='service_type',
            field=models.CharField(choices=[('2', 'Cash Withdrawal'), ('3', 'Balance Inquiry'), ('4', 'Mini Statement')], max_length=20),
        ),
    ]
