# Generated by Django 4.2.7 on 2023-12-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_aepstxncallbackbyeko_tx_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aepstxncallbackbyeko',
            name='tx_status',
            field=models.CharField(choices=[('P', 'Pending'), ('0', 'Success'), ('1', 'Failed'), ('2', 'Do_Inquiry'), ('other', 'Suspicious')], max_length=20),
        ),
    ]
