# Generated by Django 4.2.7 on 2023-12-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_remove_aepstxncallbackbyeko_user_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aepstxncallbackbyeko',
            name='amount',
        ),
    ]
