# Generated by Django 4.2.5 on 2024-01-07 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0024_bank"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bank",
        ),
    ]
