# Generated by Django 4.2.5 on 2024-01-07 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0026_dmtbanklist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DMTBankList",
        ),
    ]
