# Generated by Django 4.2.7 on 2024-01-09 05:08

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_dmtbanklist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userkycdocument',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userkycdocument',
            name='aadharBack',
            field=models.FileField(blank=True, null=True, upload_to=backend.models.document_file_path, verbose_name='Aadhar Back'),
        ),
        migrations.AddField(
            model_name='userkycdocument',
            name='aadharFront',
            field=models.FileField(blank=True, null=True, upload_to=backend.models.document_file_path, verbose_name='Aadhar Front'),
        ),
        migrations.AddField(
            model_name='userkycdocument',
            name='pancard',
            field=models.FileField(blank=True, null=True, upload_to=backend.models.document_file_path, verbose_name='Pancard'),
        ),
        migrations.RemoveField(
            model_name='userkycdocument',
            name='documentFile1',
        ),
        migrations.RemoveField(
            model_name='userkycdocument',
            name='documentFile2',
        ),
        migrations.RemoveField(
            model_name='userkycdocument',
            name='documentName',
        ),
    ]
