# Generated by Django 4.2.7 on 2024-01-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_userkycdocument_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aepstxncallbackbyeko',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Amount'),
        ),
    ]
