# Generated by Django 4.2.7 on 2024-01-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_aepstxncallbackbyeko_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='unique_sequence',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='client_ref_id',
            field=models.CharField(blank=True, max_length=500, verbose_name='Client Ref Id'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='txnId',
            field=models.CharField(blank=True, max_length=500, verbose_name='Bank Transaction Id'),
        ),
    ]
