# Generated by Django 4.2.7 on 2024-01-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_remove_wallettransaction_unique_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='txn_status',
            field=models.CharField(blank=True, max_length=500, verbose_name='Transaction Status'),
        ),
    ]
