# Generated by Django 4.2.5 on 2024-01-10 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0032_wallettransaction_txn_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PanTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=255)),
                (
                    "txn_status",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Transaction Status"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.wallet"
                    ),
                ),
            ],
        ),
    ]
