# Generated by Django 4.2.5 on 2024-01-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0033_pantransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="aepstxncallbackbyeko",
            name="tid",
            field=models.CharField(blank=True, max_length=500, verbose_name="tid"),
        ),
    ]
