# Generated by Django 4.2.5 on 2024-01-10 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0035_aepstxncallbackbyeko_aadhar_no"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PanTransaction",
            new_name="PanVerificationTxn",
        ),
        migrations.CreateModel(
            name="BankVerificationTxn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "txnId",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Bank Transaction Id"
                    ),
                ),
                (
                    "client_ref_id",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Client Ref Id"
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction_type",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Transaction Type",
                    ),
                ),
                (
                    "txn_status",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Transaction Status"
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.wallet"
                    ),
                ),
            ],
        ),
    ]
