# Generated by Django 4.2.5 on 2024-01-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0039_alter_commission_aepscommission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dmttxn",
            name="recipient_name",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Recipient Name"
            ),
        ),
    ]
