# Generated by Django 4.2.5 on 2024-01-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0040_dmttxn_recipient_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="dmttxn",
            name="commission",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="DMT Commission"
            ),
        ),
    ]
