# Generated by Django 4.2.7 on 2024-01-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_dmttxn_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aepstxncallbackbyeko',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount'),
        ),
    ]
