# Generated by Django 4.2.5 on 2024-01-26 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0043_payout"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payout",
        ),
    ]
