# Generated by Django 4.2.5 on 2024-01-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0046_remove_commission_aepscommission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aepstxncallbackbyeko",
            name="commission",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Commission",
            ),
        ),
    ]
