# Generated by Django 4.2.5 on 2024-01-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0047_aepstxncallbackbyeko_commission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commission",
            name="AepsCommissionSlab1",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Aeps 100-199 (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="AepsCommissionSlab2",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                max_digits=5,
                verbose_name="Aeps 200-999 (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="AepsCommissionSlab3",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=5,
                verbose_name="Aeps 1000-1499 (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="AepsCommissionSlab4",
            field=models.DecimalField(
                decimal_places=2,
                default=3.0,
                max_digits=5,
                verbose_name="Aeps 1500-1999 (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="AepsCommissionSlab5",
            field=models.DecimalField(
                decimal_places=2,
                default=4.0,
                max_digits=5,
                verbose_name="Aeps 2000-2499 (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="AepsCommissionSlab6",
            field=models.DecimalField(
                decimal_places=2,
                default=5.0,
                max_digits=5,
                verbose_name="Aeps 2500-2999 (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="AepsCommissionSlab7",
            field=models.DecimalField(
                decimal_places=2,
                default=7.0,
                max_digits=5,
                verbose_name="Aeps 3000-7999 (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="AepsCommissionSlab8",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                max_digits=5,
                verbose_name="Aeps 8000 & above (Rs)",
            ),
        ),
    ]
