# Generated by Django 4.2.7 on 2024-02-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0048_alter_commission_aepscommissionslab1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BbpsTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_status', models.CharField(blank=True, max_length=50, verbose_name='tx_status')),
                ('tds', models.CharField(blank=True, max_length=50, verbose_name='tds')),
                ('bbpstrxnrefid', models.CharField(blank=True, max_length=50, verbose_name='bbpstrxnrefid')),
                ('txstatus_desc', models.CharField(blank=True, max_length=50, verbose_name='txstatus_desc')),
                ('utilitycustomername', models.CharField(blank=True, max_length=50, verbose_name='utilitycustomername')),
                ('fee', models.CharField(blank=True, max_length=50, verbose_name='fee')),
                ('discount', models.CharField(blank=True, max_length=50, verbose_name='discount')),
                ('tid', models.CharField(blank=True, max_length=50, verbose_name='tid')),
                ('sender_id', models.CharField(blank=True, max_length=50, verbose_name='sender_id')),
                ('customerconveniencefee', models.CharField(blank=True, max_length=50, verbose_name='customerconveniencefee')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='state')),
                ('recipient_id', models.CharField(blank=True, max_length=50, verbose_name='recipient_id')),
                ('timestamp', models.CharField(blank=True, max_length=50, verbose_name='timestamp')),
                ('amount', models.CharField(blank=True, max_length=50, verbose_name='amount')),
                ('reference_tid', models.CharField(blank=True, max_length=50, verbose_name='reference_tid')),
                ('serial_number', models.CharField(blank=True, max_length=50, verbose_name='serial_number')),
                ('customermobilenumber', models.CharField(blank=True, max_length=50, verbose_name='customermobilenumber')),
                ('payment_mode_desc', models.CharField(blank=True, max_length=50, verbose_name='payment_mode_desc')),
                ('operator_name', models.CharField(blank=True, max_length=50, verbose_name='operator_name')),
                ('totalamount', models.CharField(blank=True, max_length=50, verbose_name='totalamount')),
                ('billnumber', models.CharField(blank=True, max_length=50, verbose_name='billnumber')),
                ('billdate', models.CharField(blank=True, max_length=50, verbose_name='billdate')),
                ('approvalreferencenumber', models.CharField(blank=True, max_length=50, verbose_name='approvalreferencenumber')),
                ('status_text', models.CharField(blank=True, max_length=50, verbose_name='status_text')),
                ('account', models.CharField(blank=True, max_length=50, verbose_name='account')),
            ],
        ),
    ]
