# Generated by Django 4.2.7 on 2024-02-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_bbpstxn_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbpstxn',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
