# Generated by Django 4.2.7 on 2024-02-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_alter_bbpstxn_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmttxn',
            name='account',
            field=models.CharField(blank=True, max_length=500, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='dmttxn',
            name='bank',
            field=models.CharField(blank=True, max_length=500, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='dmttxn',
            name='bank_ref_num',
            field=models.CharField(blank=True, max_length=500, verbose_name='Bank Ref Num'),
        ),
        migrations.AddField(
            model_name='dmttxn',
            name='channel_desc',
            field=models.CharField(blank=True, max_length=500, verbose_name='Channel Desc'),
        ),
        migrations.AddField(
            model_name='dmttxn',
            name='currency',
            field=models.CharField(blank=True, max_length=500, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='dmttxn',
            name='customer_id',
            field=models.CharField(blank=True, max_length=500, verbose_name='Customer Id'),
        ),
        migrations.AddField(
            model_name='dmttxn',
            name='recipient_id',
            field=models.CharField(blank=True, max_length=500, verbose_name='Recipient Id'),
        ),
        migrations.AddField(
            model_name='dmttxn',
            name='sender_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Sender Name'),
        ),
    ]
