# Generated by Django 4.2.5 on 2024-03-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0053_commission_aepscommissionslabdistributor1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bbpstxn",
            name="bbpstrxnrefid",
        ),
        migrations.RemoveField(
            model_name="bbpstxn",
            name="billdate",
        ),
        migrations.RemoveField(
            model_name="bbpstxn",
            name="billnumber",
        ),
        migrations.RemoveField(
            model_name="bbpstxn",
            name="customerconveniencefee",
        ),
        migrations.RemoveField(
            model_name="bbpstxn",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="bbpstxn",
            name="fee",
        ),
        migrations.RemoveField(
            model_name="bbpstxn",
            name="payment_mode_desc",
        ),
        migrations.RemoveField(
            model_name="bbpstxn",
            name="reference_tid",
        ),
        migrations.RemoveField(
            model_name="bbpstxn",
            name="serial_number",
        ),
        migrations.RemoveField(
            model_name="bbpstxn",
            name="state",
        ),
        migrations.RemoveField(
            model_name="bbpstxn",
            name="status_text",
        ),
        migrations.RemoveField(
            model_name="bbpstxn",
            name="tds",
        ),
        migrations.RemoveField(
            model_name="bbpstxn",
            name="tx_status",
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsInstantDTH",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="DTH Instant Commission",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsInstantDTHDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Distributor DTH Instant",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsInstantDTHMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Master Distributor DTH Instant",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsInstantElectricity",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Electricity Instant Commission",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsInstantElectricityDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Distributor Electricity Instant",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsInstantElectricityMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Master Distributor Electricity Instant",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsInstantLoan",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Loan Instant Commission",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsInstantLoanDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Distributor Loan Instant",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsInstantLoanMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Master Distributor Loan Instant",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsInstantRechargePostpaid",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Recharge Postpaid Instant Commission",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsInstantRechargePostpaidDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Distributor Recharge Postpaid Instant",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsInstantRechargePostpaidMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Master Distributor Recharge Postpaid Instant",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsInstantRechargePrepaid",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Recharge Prepaid Instant Commission",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsInstantRechargePrepaidDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Distributor Recharge Prepaid Instant",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsInstantRechargePrepaidMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Master Distributor Recharge Prepaid Instant",
            ),
        ),
    ]
