# Generated by Django 4.2.5 on 2024-03-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "backend",
            "0054_remove_bbpstxn_bbpstrxnrefid_remove_bbpstxn_billdate_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantDTH",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="DTH"
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantElectricity",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="Electricity"
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantLoan",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="Loan"
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantRechargePostpaid",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Recharge Postpaid",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantRechargePrepaid",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Recharge Prepaid",
            ),
        ),
    ]
