# Generated by Django 4.2.5 on 2024-03-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0055_alter_commission_bbpsinstantdth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantDTHDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Distributor DTH",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantDTHMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Master Distributor DTH",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantElectricityDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Distributor Electricity",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantElectricityMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Master Distributor Electricity",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantLoanDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Distributor Loan",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantLoanMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Master Distributor Loan",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantRechargePostpaidDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Distributor Recharge Postpaid",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantRechargePostpaidMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Master Distributor Recharge Postpaid",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantRechargePrepaidDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Distributor Recharge Prepaid",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantRechargePrepaidMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Master Distributor Recharge Prepaid",
            ),
        ),
    ]
