# Generated by Django 4.2.5 on 2024-03-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0056_alter_commission_bbpsinstantdthdistributor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantDTH",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="DTH (Rs)"
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantDTHDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Distributor DTH (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantDTHMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Master Distributor DTH (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantElectricity",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Electricity (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantElectricityDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Distributor Electricity (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantElectricityMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Master Distributor Electricity (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantLoan",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="Loan (Rs)"
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantLoanDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Distributor Loan (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantLoanMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Master Distributor Loan (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantRechargePostpaid",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Recharge Postpaid (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantRechargePostpaidDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Distributor Recharge Postpaid (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantRechargePostpaidMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Master Distributor Recharge Postpaid (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantRechargePrepaid",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Recharge Prepaid (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantRechargePrepaidDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Distributor Recharge Prepaid (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantRechargePrepaidMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Master Distributor Recharge Prepaid (Rs)",
            ),
        ),
    ]
