# Generated by Django 4.2.5 on 2024-03-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0057_alter_commission_bbpsinstantdth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commission",
            name="BbpsHCElectricity1",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Electricity 0-1000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCElectricity2",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Electricity 1001-2000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCElectricity3",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Electricity 2001-10000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCElectricity4",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Electricity 10001-15000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCElectricity5",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Electricity 15001-25000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCElectricity6",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Electricity 25001-100000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCElectricity7",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Electricity 100001-2L (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCMobilePostpaid",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Mobile Postpaid & Fixed Landline - Any Amount (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCWaterNGas1",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Water & Piped Gas Bill 0-1000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCWaterNGas2",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Water & Piped Gas Bill 1001-10000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCWaterNGas3",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Water & Piped Gas Bill 10001-15000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCWaterNGas4",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Water & Piped Gas Bill 15001-25000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCWaterNGas5",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Water & Piped Gas Bill 25001-100000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCWaterNGas6",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Water & Piped Gas Bill 100001-2L (%)",
            ),
        ),
    ]
