# Generated by Django 4.2.5 on 2024-03-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0058_commission_bbpshcelectricity1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commission",
            old_name="BbpsHCElectricity1",
            new_name="BbpsHCElectricitySlab1",
        ),
        migrations.RenameField(
            model_name="commission",
            old_name="BbpsHCElectricity2",
            new_name="BbpsHCElectricitySlab2",
        ),
        migrations.RenameField(
            model_name="commission",
            old_name="BbpsHCElectricity3",
            new_name="BbpsHCElectricitySlab3",
        ),
        migrations.RenameField(
            model_name="commission",
            old_name="BbpsHCElectricity4",
            new_name="BbpsHCElectricitySlab4",
        ),
        migrations.RenameField(
            model_name="commission",
            old_name="BbpsHCElectricity5",
            new_name="BbpsHCElectricitySlab5",
        ),
        migrations.RenameField(
            model_name="commission",
            old_name="BbpsHCElectricity6",
            new_name="BbpsHCElectricitySlab6",
        ),
        migrations.RenameField(
            model_name="commission",
            old_name="BbpsHCElectricity7",
            new_name="BbpsHCElectricitySlab7",
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCElectricitySlabDistributor1",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Distributor Electricity 0-1000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCElectricitySlabDistributor2",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Distributor Electricity 1001-2000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCElectricitySlabDistributor3",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Distributor Electricity 2001-10000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCElectricitySlabDistributor4",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Distributor Electricity 10001-15000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCElectricitySlabDistributor5",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Distributor Electricity 15001-25000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCElectricitySlabDistributor6",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Distributor Electricity 25001-100000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCElectricitySlabDistributor7",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Distributor Electricity 100001-2L (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCElectricitySlabMaster1",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Master Electricity 0-1000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCElectricitySlabMaster2",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Master Electricity 1001-2000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCElectricitySlabMaster3",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Master Electricity 2001-10000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCElectricitySlabMaster4",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Master Electricity 10001-15000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCElectricitySlabMaster5",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Master Electricity 15001-25000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCElectricitySlabMaster6",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Master Electricity 25001-100000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCElectricitySlabMaster7",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Master Electricity 100001-2L (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCMobilePostpaidDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Distributor Mobile Postpaid & Fixed Landline - Any Amount (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCMobilePostpaidMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Master Mobile Postpaid & Fixed Landline - Any Amount (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCWaterNGasDistributor1",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Distributor Water & Piped Gas Bill 0-1000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCWaterNGasDistributor2",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Distributor Water & Piped Gas Bill 1001-10000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCWaterNGasDistributor3",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Distributor Water & Piped Gas Bill 10001-15000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCWaterNGasDistributor4",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Distributor Water & Piped Gas Bill 15001-25000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCWaterNGasDistributor5",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Distributor Water & Piped Gas Bill 25001-100000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCWaterNGasDistributor6",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Distributor Water & Piped Gas Bill 100001-2L (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCWaterNGasMaster1",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Master Water & Piped Gas Bill 0-1000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCWaterNGasMaster2",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Master Water & Piped Gas Bill 1001-10000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCWaterNGasMaster3",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Master Water & Piped Gas Bill 10001-15000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCWaterNGasMaster4",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Master Water & Piped Gas Bill 15001-25000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCWaterNGasMaster5",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Master Water & Piped Gas Bill 25001-100000 (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="BbpsHCWaterNGasMaster6",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="High Commission Master Water & Piped Gas Bill 100001-2L (%)",
            ),
        ),
    ]
