# Generated by Django 4.2.7 on 2024-03-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0061_commission_bbpshcairtelmobileprepaid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='BbpsHCDTHAirtelDTv',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='High Commission Airtel Dish TV - Any Amount (%)'),
        ),
        migrations.AddField(
            model_name='commission',
            name='BbpsHCDTHAirtelDTvDistributor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='High Commission Distributor Airtel Dish TV - Any Amount (%)'),
        ),
        migrations.AddField(
            model_name='commission',
            name='BbpsHCDTHAirtelDTvMaster',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='High Commission Master Airtel Dish TV - Any Amount (%)'),
        ),
        migrations.AddField(
            model_name='commission',
            name='BbpsHCDTHDishTv',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='High Commission Dish TV - Any Amount (%)'),
        ),
        migrations.AddField(
            model_name='commission',
            name='BbpsHCDTHDishTvDistributor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='High Commission Distributor Dish TV - Any Amount (%)'),
        ),
        migrations.AddField(
            model_name='commission',
            name='BbpsHCDTHDishTvMaster',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='High Commission Master Dish TV - Any Amount (%)'),
        ),
        migrations.AddField(
            model_name='commission',
            name='BbpsHCDTHTataSky',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='High Commission TataSky - Any Amount (%)'),
        ),
        migrations.AddField(
            model_name='commission',
            name='BbpsHCDTHTataSkyDistributor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='High Commission Distributor TataSky - Any Amount (%)'),
        ),
        migrations.AddField(
            model_name='commission',
            name='BbpsHCDTHTataSkyMaster',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='High Commission Master TataSky - Any Amount (%)'),
        ),
        migrations.AddField(
            model_name='commission',
            name='BbpsHCDTHVideoconTv',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='High Commission Videocon TV - Any Amount (%)'),
        ),
        migrations.AddField(
            model_name='commission',
            name='BbpsHCDTHVideoconTvDistributor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='High Commission Distributor Videocon TV - Any Amount (%)'),
        ),
        migrations.AddField(
            model_name='commission',
            name='BbpsHCDTHVideoconTvMaster',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='High Commission Master Videocon TV - Any Amount (%)'),
        ),
        migrations.AddField(
            model_name='commission',
            name='BbpsHCLIC',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='High Commission LIC Offline - Any Amount (%)'),
        ),
        migrations.AddField(
            model_name='commission',
            name='BbpsHCLICDistributor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='High Commission Distributor LIC Offline - Any Amount (%)'),
        ),
        migrations.AddField(
            model_name='commission',
            name='BbpsHCLICMaster',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='High Commission Master LIC Offline - Any Amount (%)'),
        ),
    ]
