# Generated by Django 4.2.7 on 2024-03-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_commission_bbpshcdthairteldtv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='BbpsHCLIC',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='BbpsHCLICDistributor',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='BbpsHCLICMaster',
        ),
    ]
