# Generated by Django 4.2.7 on 2024-03-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_remove_commission_bbpshclic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='BbpsHCDTHBigTv',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='High Commission Big TV - Any Amount (%)'),
        ),
        migrations.AddField(
            model_name='commission',
            name='BbpsHCDTHBigTvDistributor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='High Commission Distributor Big TV - Any Amount (%)'),
        ),
        migrations.AddField(
            model_name='commission',
            name='BbpsHCDTHBigTvMaster',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='High Commission Master Big TV - Any Amount (%)'),
        ),
    ]
