# Generated by Django 4.2.7 on 2024-03-16 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0066_remove_cmstxncallbackbyeko_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmstxncallbackbyeko',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
