# Generated by Django 4.2.7 on 2024-03-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0067_cmstxncallbackbyeko_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmstxncallbackbyeko',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
