# Generated by Django 4.2.7 on 2024-03-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0068_alter_cmstxncallbackbyeko_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrtxncallbackbyeko',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='qrtxncallbackbyeko',
            name='bank_ref_num',
        ),
        migrations.RemoveField(
            model_name='qrtxncallbackbyeko',
            name='client_ref_id',
        ),
        migrations.RemoveField(
            model_name='qrtxncallbackbyeko',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='qrtxncallbackbyeko',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='qrtxncallbackbyeko',
            name='old_tx_status',
        ),
        migrations.RemoveField(
            model_name='qrtxncallbackbyeko',
            name='old_tx_status_desc',
        ),
        migrations.RemoveField(
            model_name='qrtxncallbackbyeko',
            name='partners_commision',
        ),
        migrations.RemoveField(
            model_name='qrtxncallbackbyeko',
            name='service_code',
        ),
        migrations.RemoveField(
            model_name='qrtxncallbackbyeko',
            name='tds',
        ),
        migrations.RemoveField(
            model_name='qrtxncallbackbyeko',
            name='tid',
        ),
        migrations.RemoveField(
            model_name='qrtxncallbackbyeko',
            name='tx_status',
        ),
        migrations.RemoveField(
            model_name='qrtxncallbackbyeko',
            name='txstatus_desc',
        ),
        migrations.AddField(
            model_name='qrtxncallbackbyeko',
            name='txn_detail',
            field=models.JSONField(default={}, verbose_name='Transaction JSON'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qrtxncallbackbyeko',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
