# Generated by Django 4.2.5 on 2024-04-21 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0069_remove_qrtxncallbackbyeko_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCardTxn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "txn_status",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Transaction Status"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "sender_name",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Sender Name"
                    ),
                ),
                (
                    "txnId",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Bank Transaction Id"
                    ),
                ),
                (
                    "client_ref_id",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Client Ref Id"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Recipient Name"
                    ),
                ),
                (
                    "ifsc",
                    models.CharField(blank=True, max_length=500, verbose_name="IFSC"),
                ),
                (
                    "bank_ref_num",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Bank Ref Num"
                    ),
                ),
                (
                    "account",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Account Number"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "commission",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Credit Card Commission",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.wallet"
                    ),
                ),
            ],
        ),
    ]
