# Generated by Django 4.2.5 on 2024-04-21 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0070_creditcardtxn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creditcardtxn",
            name="commission",
        ),
    ]
