# Generated by Django 4.2.5 on 2024-05-05 07:50

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0073_adhaarverificationtxn"),
    ]

    operations = [
        migrations.AddField(
            model_name="userkycdocument",
            name="cancelChequePassbook",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=backend.models.document_file_path,
                verbose_name="Cancel Cheque/Passbook",
            ),
        ),
        migrations.AddField(
            model_name="userkycdocument",
            name="declarationForm",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=backend.models.document_file_path,
                verbose_name="Self Declaration Form",
            ),
        ),
        migrations.AddField(
            model_name="userkycdocument",
            name="photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=backend.models.document_file_path,
                verbose_name="Passport Size Photo",
            ),
        ),
        migrations.AddField(
            model_name="userkycdocument",
            name="policVerification",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=backend.models.document_file_path,
                verbose_name="Polic Verification",
            ),
        ),
    ]
