# Generated by Django 4.2.5 on 2024-05-05 07:52

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0074_userkycdocument_cancelchequepassbook_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userkycdocument",
            name="policVerification",
        ),
        migrations.AddField(
            model_name="userkycdocument",
            name="policeVerification",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=backend.models.document_file_path,
                verbose_name="Police Verification",
            ),
        ),
    ]
