# Generated by Django 4.2.5 on 2024-05-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0075_remove_userkycdocument_policverification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCAirtelMobilePrepaid",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=10,
                verbose_name="High Commission Airtel Mobile Prepaid - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCAirtelMobilePrepaidDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                max_digits=10,
                verbose_name="High Commission Distributor Airtel Mobile Prepaid - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCAirtelMobilePrepaidMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                max_digits=10,
                verbose_name="High Commission Master Airtel Mobile Prepaid - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCBSNLMobilePrepaid",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=10,
                verbose_name="High Commission BSNL Mobile Prepaid - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCBSNLMobilePrepaidDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                max_digits=10,
                verbose_name="High Commission Distributor BSNL Mobile Prepaid - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCBSNLMobilePrepaidMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                max_digits=10,
                verbose_name="High Commission Master BSNL Mobile Prepaid - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCDTHAirtelDTv",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                max_digits=10,
                verbose_name="High Commission Airtel Dish TV - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCDTHAirtelDTvDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                max_digits=10,
                verbose_name="High Commission Distributor Airtel Dish TV - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCDTHAirtelDTvMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                max_digits=10,
                verbose_name="High Commission Master Airtel Dish TV - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCDTHBigTv",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                max_digits=10,
                verbose_name="High Commission Big TV - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCDTHBigTvDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                max_digits=10,
                verbose_name="High Commission Distributor Big TV - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCDTHBigTvMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                max_digits=10,
                verbose_name="High Commission Master Big TV - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCDTHDishTv",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                max_digits=10,
                verbose_name="High Commission Dish TV - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCDTHDishTvDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                max_digits=10,
                verbose_name="High Commission Distributor Dish TV - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCDTHDishTvMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                max_digits=10,
                verbose_name="High Commission Master Dish TV - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCDTHTataSky",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                max_digits=10,
                verbose_name="High Commission TataSky - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCDTHTataSkyDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                max_digits=10,
                verbose_name="High Commission Distributor TataSky - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCDTHTataSkyMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                max_digits=10,
                verbose_name="High Commission Master TataSky - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCDTHVideoconTv",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                max_digits=10,
                verbose_name="High Commission Videocon TV - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCDTHVideoconTvDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                max_digits=10,
                verbose_name="High Commission Distributor Videocon TV - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCDTHVideoconTvMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                max_digits=10,
                verbose_name="High Commission Master Videocon TV - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCElectricitySlab1",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                max_digits=10,
                verbose_name="High Commission Electricity 0-1000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCElectricitySlab2",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                max_digits=10,
                verbose_name="High Commission Electricity 1001-2000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCElectricitySlab3",
            field=models.DecimalField(
                decimal_places=2,
                default=0.15,
                max_digits=10,
                verbose_name="High Commission Electricity 2001-10000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCElectricitySlab4",
            field=models.DecimalField(
                decimal_places=2,
                default=0.15,
                max_digits=10,
                verbose_name="High Commission Electricity 10001-15000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCElectricitySlab5",
            field=models.DecimalField(
                decimal_places=2,
                default=0.2,
                max_digits=10,
                verbose_name="High Commission Electricity 15001-25000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCElectricitySlab6",
            field=models.DecimalField(
                decimal_places=2,
                default=0.2,
                max_digits=10,
                verbose_name="High Commission Electricity 25001-100000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCElectricitySlab7",
            field=models.DecimalField(
                decimal_places=2,
                default=0.2,
                max_digits=10,
                verbose_name="High Commission Electricity 100001-2L (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCElectricitySlabDistributor1",
            field=models.DecimalField(
                decimal_places=2,
                default=0.03,
                max_digits=10,
                verbose_name="High Commission Distributor Electricity 0-1000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCElectricitySlabDistributor2",
            field=models.DecimalField(
                decimal_places=2,
                default=0.03,
                max_digits=10,
                verbose_name="High Commission Distributor Electricity 1001-2000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCElectricitySlabDistributor3",
            field=models.DecimalField(
                decimal_places=2,
                default=0.04,
                max_digits=10,
                verbose_name="High Commission Distributor Electricity 2001-10000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCElectricitySlabDistributor4",
            field=models.DecimalField(
                decimal_places=2,
                default=0.04,
                max_digits=10,
                verbose_name="High Commission Distributor Electricity 10001-15000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCElectricitySlabDistributor5",
            field=models.DecimalField(
                decimal_places=2,
                default=0.05,
                max_digits=10,
                verbose_name="High Commission Distributor Electricity 15001-25000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCElectricitySlabDistributor6",
            field=models.DecimalField(
                decimal_places=2,
                default=0.05,
                max_digits=10,
                verbose_name="High Commission Distributor Electricity 25001-100000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCElectricitySlabDistributor7",
            field=models.DecimalField(
                decimal_places=2,
                default=0.05,
                max_digits=10,
                verbose_name="High Commission Distributor Electricity 100001-2L (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCElectricitySlabMaster1",
            field=models.DecimalField(
                decimal_places=2,
                default=0.03,
                max_digits=10,
                verbose_name="High Commission Master Electricity 0-1000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCElectricitySlabMaster2",
            field=models.DecimalField(
                decimal_places=2,
                default=0.03,
                max_digits=10,
                verbose_name="High Commission Master Electricity 1001-2000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCElectricitySlabMaster3",
            field=models.DecimalField(
                decimal_places=2,
                default=0.04,
                max_digits=10,
                verbose_name="High Commission Master Electricity 2001-10000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCElectricitySlabMaster4",
            field=models.DecimalField(
                decimal_places=2,
                default=0.04,
                max_digits=10,
                verbose_name="High Commission Master Electricity 10001-15000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCElectricitySlabMaster5",
            field=models.DecimalField(
                decimal_places=2,
                default=0.05,
                max_digits=10,
                verbose_name="High Commission Master Electricity 15001-25000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCElectricitySlabMaster6",
            field=models.DecimalField(
                decimal_places=2,
                default=0.05,
                max_digits=10,
                verbose_name="High Commission Master Electricity 25001-100000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCElectricitySlabMaster7",
            field=models.DecimalField(
                decimal_places=2,
                default=0.05,
                max_digits=10,
                verbose_name="High Commission Master Electricity 100001-2L (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCJioMobilePrepaid",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=10,
                verbose_name="High Commission JIO Mobile Prepaid - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCJioMobilePrepaidDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                max_digits=10,
                verbose_name="High Commission Distributor JIO Mobile Prepaid - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCJioMobilePrepaidMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                max_digits=10,
                verbose_name="High Commission Master JIO Mobile Prepaid - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCMTNLMobilePrepaid",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=10,
                verbose_name="High Commission MTNL Delhi & Mumbai Mobile Prepaid - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCMTNLMobilePrepaidDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                max_digits=10,
                verbose_name="High Commission Distributor MTNL Delhi & Mumbai Mobile Prepaid - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCMTNLMobilePrepaidMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                max_digits=10,
                verbose_name="High Commission Master MTNL Delhi & Mumbai Mobile Prepaid - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCMobilePostpaid",
            field=models.DecimalField(
                decimal_places=2,
                default=0.15,
                max_digits=10,
                verbose_name="High Commission Mobile Postpaid & Fixed Landline - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCMobilePostpaidDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.05,
                max_digits=10,
                verbose_name="High Commission Distributor Mobile Postpaid & Fixed Landline - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCMobilePostpaidMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.05,
                max_digits=10,
                verbose_name="High Commission Master Mobile Postpaid & Fixed Landline - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCVIMobilePrepaid",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=10,
                verbose_name="High Commission VI Mobile Prepaid - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCVIMobilePrepaidDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                max_digits=10,
                verbose_name="High Commission Distributor VI Mobile Prepaid - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCVIMobilePrepaidMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                max_digits=10,
                verbose_name="High Commission Master VI Mobile Prepaid - Any Amount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCWaterNGasSlab1",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                max_digits=10,
                verbose_name="High Commission Water & Piped Gas Bill 0-1000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCWaterNGasSlab2",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                max_digits=10,
                verbose_name="High Commission Water & Piped Gas Bill 1001-10000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCWaterNGasSlab3",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                max_digits=10,
                verbose_name="High Commission Water & Piped Gas Bill 10001-15000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCWaterNGasSlab4",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                max_digits=10,
                verbose_name="High Commission Water & Piped Gas Bill 15001-25000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCWaterNGasSlab5",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                max_digits=10,
                verbose_name="High Commission Water & Piped Gas Bill 25001-100000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCWaterNGasSlab6",
            field=models.DecimalField(
                decimal_places=2,
                default=0.1,
                max_digits=10,
                verbose_name="High Commission Water & Piped Gas Bill 100001-2L (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCWaterNGasSlabDistributor1",
            field=models.DecimalField(
                decimal_places=2,
                default=0.03,
                max_digits=10,
                verbose_name="High Commission Distributor Water & Piped Gas Bill 0-1000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCWaterNGasSlabDistributor2",
            field=models.DecimalField(
                decimal_places=2,
                default=0.03,
                max_digits=10,
                verbose_name="High Commission Distributor Water & Piped Gas Bill 1001-10000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCWaterNGasSlabDistributor3",
            field=models.DecimalField(
                decimal_places=2,
                default=0.03,
                max_digits=10,
                verbose_name="High Commission Distributor Water & Piped Gas Bill 10001-15000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCWaterNGasSlabDistributor4",
            field=models.DecimalField(
                decimal_places=2,
                default=0.03,
                max_digits=10,
                verbose_name="High Commission Distributor Water & Piped Gas Bill 15001-25000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCWaterNGasSlabDistributor5",
            field=models.DecimalField(
                decimal_places=2,
                default=0.03,
                max_digits=10,
                verbose_name="High Commission Distributor Water & Piped Gas Bill 25001-100000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCWaterNGasSlabDistributor6",
            field=models.DecimalField(
                decimal_places=2,
                default=0.03,
                max_digits=10,
                verbose_name="High Commission Distributor Water & Piped Gas Bill 100001-2L (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCWaterNGasSlabMaster1",
            field=models.DecimalField(
                decimal_places=2,
                default=0.02,
                max_digits=10,
                verbose_name="High Commission Master Water & Piped Gas Bill 0-1000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCWaterNGasSlabMaster2",
            field=models.DecimalField(
                decimal_places=2,
                default=0.02,
                max_digits=10,
                verbose_name="High Commission Master Water & Piped Gas Bill 1001-10000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCWaterNGasSlabMaster3",
            field=models.DecimalField(
                decimal_places=2,
                default=0.02,
                max_digits=10,
                verbose_name="High Commission Master Water & Piped Gas Bill 10001-15000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCWaterNGasSlabMaster4",
            field=models.DecimalField(
                decimal_places=2,
                default=0.02,
                max_digits=10,
                verbose_name="High Commission Master Water & Piped Gas Bill 15001-25000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCWaterNGasSlabMaster5",
            field=models.DecimalField(
                decimal_places=2,
                default=0.02,
                max_digits=10,
                verbose_name="High Commission Master Water & Piped Gas Bill 25001-100000 (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsHCWaterNGasSlabMaster6",
            field=models.DecimalField(
                decimal_places=2,
                default=0.02,
                max_digits=10,
                verbose_name="High Commission Master Water & Piped Gas Bill 100001-2L (%)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantDTH",
            field=models.DecimalField(
                decimal_places=2, default=1.0, max_digits=5, verbose_name="DTH (Rs)"
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantDTHDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.3,
                max_digits=5,
                verbose_name="Distributor DTH (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantDTHMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.2,
                max_digits=5,
                verbose_name="Master Distributor DTH (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantElectricity",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=5,
                verbose_name="Electricity (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantElectricityDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.3,
                max_digits=5,
                verbose_name="Distributor Electricity (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantElectricityMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.2,
                max_digits=5,
                verbose_name="Master Distributor Electricity (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantLoan",
            field=models.DecimalField(
                decimal_places=2, default=1.0, max_digits=5, verbose_name="Loan (Rs)"
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantLoanDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.3,
                max_digits=5,
                verbose_name="Distributor Loan (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantLoanMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.2,
                max_digits=5,
                verbose_name="Master Distributor Loan (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantRechargePostpaid",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=5,
                verbose_name="Recharge Postpaid (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantRechargePostpaidDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.3,
                max_digits=5,
                verbose_name="Distributor Recharge Postpaid (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantRechargePostpaidMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.2,
                max_digits=5,
                verbose_name="Master Distributor Recharge Postpaid (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantRechargePrepaid",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=5,
                verbose_name="Recharge Prepaid (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantRechargePrepaidDistributor",
            field=models.DecimalField(
                decimal_places=2,
                default=0.3,
                max_digits=5,
                verbose_name="Distributor Recharge Prepaid (Rs)",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="BbpsInstantRechargePrepaidMaster",
            field=models.DecimalField(
                decimal_places=2,
                default=0.2,
                max_digits=5,
                verbose_name="Master Distributor Recharge Prepaid (Rs)",
            ),
        ),
    ]
