# Generated by Django 4.2.5 on 2024-05-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0076_alter_commission_bbpshcairtelmobileprepaid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherServices2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serviceName",
                    models.CharField(max_length=150, verbose_name="Service Name"),
                ),
                (
                    "serviceUrl",
                    models.CharField(max_length=500, verbose_name="Service URL"),
                ),
            ],
        ),
    ]
