# Generated by Django 4.2.5 on 2024-05-09 15:31

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0077_otherservices2"),
    ]

    operations = [
        migrations.AddField(
            model_name="otherservices",
            name="address",
            field=models.CharField(blank=True, max_length=100, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="otherservices",
            name="adhaar",
            field=models.CharField(blank=True, max_length=100, verbose_name="Adhaar"),
        ),
        migrations.AddField(
            model_name="otherservices",
            name="dob",
            field=models.CharField(blank=True, max_length=100, verbose_name="DOB"),
        ),
        migrations.AddField(
            model_name="otherservices",
            name="doc1",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=backend.models.other_service_file_path,
                verbose_name="Supporting Document 1",
            ),
        ),
        migrations.AddField(
            model_name="otherservices",
            name="doc2",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=backend.models.other_service_file_path,
                verbose_name="Supporting Document 2",
            ),
        ),
        migrations.AddField(
            model_name="otherservices",
            name="doc3",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=backend.models.other_service_file_path,
                verbose_name="Supporting Document 3",
            ),
        ),
        migrations.AddField(
            model_name="otherservices",
            name="doc4",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=backend.models.other_service_file_path,
                verbose_name="Supporting Document 4",
            ),
        ),
        migrations.AddField(
            model_name="otherservices",
            name="email",
            field=models.CharField(blank=True, max_length=100, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="otherservices",
            name="father_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Father's name"
            ),
        ),
        migrations.AddField(
            model_name="otherservices",
            name="gender",
            field=models.CharField(blank=True, max_length=100, verbose_name="Gender"),
        ),
        migrations.AddField(
            model_name="otherservices",
            name="mobile",
            field=models.CharField(blank=True, max_length=100, verbose_name="Mobile"),
        ),
        migrations.AddField(
            model_name="otherservices",
            name="name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="otherservices",
            name="pan",
            field=models.CharField(blank=True, max_length=100, verbose_name="pan"),
        ),
    ]
