# Generated by Django 4.2.10 on 2024-08-15 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0079_alter_otherservices_doc1_alter_otherservices_doc2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaySprintMerchantAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bank2_registered', models.BooleanField(default=False)),
                ('is_bank3_registered', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('bank2_last_authentication_date', models.DateTimeField(blank=True, null=True)),
                ('bank3_last_authentication_date', models.DateTimeField(blank=True, null=True)),
                ('bank2_MerAuthTxnId', models.CharField(blank=True, max_length=255, null=True)),
                ('bank3_MerAuthTxnId', models.CharField(blank=True, max_length=255, null=True)),
                ('userAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaySprintCashWithdrawlTransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ack_no', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_rrn', models.CharField(blank=True, max_length=255, null=True)),
                ('txn_status', models.CharField(blank=True, max_length=255, null=True)),
                ('userAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaySprintAadharPayTransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ack_no', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('balance_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_rrn', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_iin', models.CharField(blank=True, max_length=255, null=True)),
                ('userAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
