# Generated by Django 4.2.10 on 2024-08-17 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0080_paysprintmerchantauth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='api_type',
            field=models.CharField(choices=[('ecko', 'Primary'), ('pay_sprint', 'Relative')], default='ecko', max_length=10, verbose_name='Payout API Type'),
        ),
        migrations.CreateModel(
            name='PaySprintPayoutBankAccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bene_id', models.CharField(max_length=255, null=True, unique=True, verbose_name='Beneficiary Id')),
                ('account', models.CharField(max_length=255, null=True, verbose_name='Account Number')),
                ('bankid', models.CharField(max_length=255, null=True, verbose_name='DMT Bank Id')),
                ('ifsc', models.CharField(max_length=255, null=True, verbose_name='IFSC Code')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Beneficiary Name')),
                ('account_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('RELATIVE', 'Relative')], default='PRIMARY', max_length=10, verbose_name='Account Type')),
                ('acc_status', models.CharField(choices=[('0', 'Account Deactivated'), ('1', 'Account Activated'), ('2', 'Document Upload Pending'), ('3', 'Document Verification pending at admin end')], default='2', max_length=10, verbose_name='Account Status')),
                ('userAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
