# Generated by Django 4.2.10 on 2024-08-21 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0081_payout_api_type_paysprintpayoutbankaccountdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaySprintAEPSTxnDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(blank=True, default='N/A', max_length=500, verbose_name='Reference No')),
                ('txn_status', models.CharField(choices=[('0', 'Failed'), ('1', 'Success'), ('2', 'Pending'), ('3', 'Transaction Not found in system'), ('other', 'Bad request, Try again')], default='2', max_length=20)),
                ('message', models.CharField(blank=True, default='N/A', max_length=500, verbose_name='Message')),
                ('ack_no', models.CharField(blank=True, max_length=500, null=True, verbose_name='ack_no')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount')),
                ('balance_amount', models.CharField(blank=True, default='N/A', max_length=20, verbose_name='Balance Amount')),
                ('bank_rrn', models.CharField(blank=True, default='N/A', max_length=500, verbose_name='bank_rrn')),
                ('bank_iin', models.CharField(blank=True, default='N/A', max_length=255, verbose_name='bank_iin')),
                ('service_type', models.CharField(choices=[('1', 'Aadhaar Pay'), ('2', 'Cash Withdrawal'), ('3', 'Balance Inquiry'), ('4', 'Mini Statement')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('userAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Linked User')),
            ],
        ),
        migrations.CreateModel(
            name='PaySprintPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='Reference ID')),
                ('ack_no', models.CharField(blank=True, max_length=500, null=True, verbose_name='Acknowledgement Number')),
                ('bank_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Bank Name')),
                ('account_no', models.CharField(blank=True, max_length=500, null=True, verbose_name='Account Number')),
                ('beneficiary_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Beneficiary Name')),
                ('amount', models.CharField(blank=True, max_length=500, null=True, verbose_name='Amount')),
                ('ifsc', models.CharField(blank=True, max_length=500, null=True, verbose_name='IFSC')),
                ('mode', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mode')),
                ('charges', models.CharField(blank=True, max_length=500, null=True, verbose_name='Charges')),
                ('utr', models.CharField(blank=True, max_length=500, null=True, verbose_name='UTR')),
                ('txn_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Txn Status')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('userAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Linked User')),
            ],
        ),
        migrations.RemoveField(
            model_name='paysprintcashwithdrawltransactiondetails',
            name='userAccount',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='api_type',
        ),
        migrations.DeleteModel(
            name='PaySprintAadharPayTransactionDetails',
        ),
        migrations.DeleteModel(
            name='PaySprintCashWithdrawlTransactionDetails',
        ),
    ]
