# Generated by Django 4.2.10 on 2024-08-21 20:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0082_paysprintaepstxndetails_paysprintpayout_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaySprintAEPSTxnDetails',
            new_name='PaySprintAEPSTxnDetail',
        ),
    ]
