# Generated by Django 4.2.10 on 2024-09-21 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0083_rename_paysprintaepstxndetails_paysprintaepstxndetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('userAccount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='paysprintaepstxndetail',
            name='ack_no',
            field=models.CharField(blank=True, default='N/A', max_length=500, null=True, verbose_name='ack_no'),
        ),
        migrations.AlterField(
            model_name='paysprintaepstxndetail',
            name='balance_amount',
            field=models.CharField(blank=True, default='0.0', max_length=20, verbose_name='Balance Amount'),
        ),
        migrations.CreateModel(
            name='Wallet2Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('txnId', models.CharField(blank=True, max_length=500, verbose_name='Bank Transaction Id')),
                ('client_ref_id', models.CharField(blank=True, max_length=500, verbose_name='Client Ref Id')),
                ('description', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(blank=True, max_length=500, null=True, verbose_name='Transaction Type')),
                ('txn_status', models.CharField(blank=True, max_length=500, verbose_name='Transaction Status')),
                ('wallet2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.wallet2')),
            ],
        ),
    ]
