# Generated by Django 4.2.10 on 2024-09-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0084_paysprintcommissioncharge_wallet2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paysprintcommissioncharge',
            name='slab_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paysprintcommissioncharge',
            name='slab_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
