# Generated by Django 4.2.10 on 2024-09-22 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0085_alter_paysprintcommissioncharge_slab_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaySprintCommissionTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=500, verbose_name='Amount')),
                ('txn_status', models.CharField(blank=True, max_length=50, verbose_name='Txn Status')),
                ('desc', models.CharField(max_length=50, verbose_name='Commission Description')),
                ('agent_name', models.CharField(blank=True, max_length=500, verbose_name='Agent Name')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('userAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Linked User')),
            ],
        ),
    ]
