# Generated by Django 4.2.10 on 2024-09-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0086_paysprintcommissiontxn'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet2',
            name='hold_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet2',
            name='is_hold',
            field=models.BooleanField(default=False),
        ),
    ]
