# Generated by Django 4.2.10 on 2024-09-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0087_wallet2_hold_reason_wallet2_is_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysprintaepstxndetail',
            name='aadhaar_no',
            field=models.CharField(default='N/A', max_length=12, verbose_name='Aadhaar No.'),
        ),
    ]
