# Generated by Django 4.2.10 on 2024-10-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0088_paysprintaepstxndetail_aadhaar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paysprintaepstxndetail',
            name='aadhaar_no',
            field=models.CharField(default='N/A', max_length=12, null=True, verbose_name='Aadhaar No.'),
        ),
        migrations.AlterField(
            model_name='paysprintaepstxndetail',
            name='bank_iin',
            field=models.CharField(blank=True, default='N/A', max_length=255, null=True, verbose_name='bank_iin'),
        ),
        migrations.AlterField(
            model_name='paysprintaepstxndetail',
            name='bank_rrn',
            field=models.CharField(blank=True, default='N/A', max_length=500, null=True, verbose_name='bank_rrn'),
        ),
        migrations.AlterField(
            model_name='paysprintaepstxndetail',
            name='message',
            field=models.CharField(blank=True, default='N/A', max_length=500, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='paysprintaepstxndetail',
            name='reference_no',
            field=models.CharField(blank=True, default='N/A', max_length=500, null=True, verbose_name='Reference No'),
        ),
        migrations.AlterField(
            model_name='paysprintcommissioncharge',
            name='service_type',
            field=models.CharField(choices=[('AEPS', 'AEPS'), ('Mini Statement', 'Mini Statement'), ('Aadhaar Pay', 'Aadhaar Pay'), ('Payout', 'Payout'), ('Onboarding', 'Onboarding'), ('Daily KYC', 'Daily KYC')], max_length=20),
        ),
    ]
