# Generated by Django 4.2.10 on 2024-11-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0090_remove_wallet2_is_hold_wallet2_held_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet2transaction',
            name='txnId',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Bank Transaction Id'),
        ),
    ]
